apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: celery-worker-keda-autoscaler
  namespace: multi-agent-exam
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: exam-portal-celery-worker
  minReplicaCount: 2
  maxReplicaCount: 16
  pollingInterval: 15
  cooldownPeriod: 60
  triggers:
    - type: redis
      metadata:
        addressFromEnv: REDIS_BROKER_URL
        listName: celery
        listLength: "5"
