apiVersion: batch/v1
kind: Job
metadata:
  name: database-migration-job
  namespace: multi-agent-exam
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: db-migrator
          image: multi-agent-exam-portal-backend:1.0.0
          command: ["python", "-c", "from app.database.session import Base, engine; Base.metadata.create_all(bind=engine); print('Database Migration Job Succeeded.')"]
          envFrom:
            - configMapRef:
                name: exam-portal-config
            - secretRef:
                name: exam-portal-secrets
