import unittest
from app.schemas.question import CandidateQuestionResponseSchema, RecruiterQuestionResponseSchema

try:
    from app.pipeline.tasks import MCPContextInjector
    HAS_TASKS = True
except (ImportError, ModuleNotFoundError):
    HAS_TASKS = False

class TestSecurityHardening(unittest.TestCase):

    def test_candidate_question_schema_hides_expected_outputs(self):
        schema_fields = set(CandidateQuestionResponseSchema.model_fields.keys())
        self.assertNotIn("expected_output", schema_fields)
        self.assertNotIn("input_data", schema_fields)
        self.assertNotIn("is_hidden", schema_fields)

    def test_mcp_path_traversal_rejection(self):
        if not HAS_TASKS:
            self.skipTest("Celery dependency not available on host environment.")
        with self.assertRaises(ValueError):
            MCPContextInjector.sanitize_path("../../etc/passwd")

        with self.assertRaises(ValueError):
            MCPContextInjector.sanitize_path("/etc/shadow")

    def test_normal_ascii_password(self):
        from app.core.security import get_password_hash, verify_password
        hashed = get_password_hash("SecretPass123!")
        self.assertTrue(verify_password("SecretPass123!", hashed))
        self.assertFalse(verify_password("WrongPassword", hashed))

    def test_exact_72_byte_password(self):
        from app.core.security import get_password_hash, verify_password
        exact_72 = "a" * 72
        hashed = get_password_hash(exact_72)
        self.assertTrue(verify_password(exact_72, hashed))

    def test_greater_than_72_byte_ascii_password(self):
        from app.core.security import get_password_hash, verify_password
        long_pwd = "a" * 120
        hashed = get_password_hash(long_pwd)
        self.assertTrue(verify_password(long_pwd, hashed))
        self.assertTrue(verify_password("a" * 72, hashed))

    def test_unicode_password(self):
        from app.core.security import get_password_hash, verify_password
        unicode_pwd = "Password🔒123🔑"
        hashed = get_password_hash(unicode_pwd)
        self.assertTrue(verify_password(unicode_pwd, hashed))

    def test_greater_than_72_byte_unicode_password(self):
        from app.core.security import get_password_hash, verify_password, _get_password_bytes
        unicode_long = "😀" * 30  # 30 * 4 bytes = 120 bytes
        pwd_bytes = _get_password_bytes(unicode_long)
        self.assertLessEqual(len(pwd_bytes), 72)
        # Verify it decodes cleanly without UnicodeDecodeError
        pwd_bytes.decode('utf-8')
        hashed = get_password_hash(unicode_long)
        self.assertTrue(verify_password(unicode_long, hashed))

    def test_incorrect_password_rejection(self):
        from app.core.security import get_password_hash, verify_password
        hashed = get_password_hash("CorrectPassword")
        self.assertFalse(verify_password("IncorrectPassword", hashed))

    def test_legacy_passlib_bcrypt_hash_compatibility(self):
        from app.core.security import verify_password
        import bcrypt
        # Standard $2b$ hash generated by passlib/bcrypt
        legacy_hash = bcrypt.hashpw(b"legacy_secret_123", bcrypt.gensalt()).decode('utf-8')
        self.assertTrue(verify_password("legacy_secret_123", legacy_hash))

    def test_passlib_bcrypt_regression_no_value_error(self):
        from app.core.security import get_password_hash
        try:
            hashed = get_password_hash("testpassword123")
            self.assertTrue(hashed.startswith("$2b$") or hashed.startswith("$2a$"))
        except ValueError as e:
            self.fail(f"get_password_hash raised ValueError: {e}")

if __name__ == "__main__":
    unittest.main()
