export type RealtimeEventType =
  | 'EXAM_STARTED'
  | 'EXAM_TIME_WARNING'
  | 'EXAM_EXPIRED'
  | 'QUESTION_OPENED'
  | 'QUESTION_COMPLETED'
  | 'CODE_SAVED'
  | 'SUBMISSION_CREATED'
  | 'SUBMISSION_QUEUED'
  | 'EVALUATION_STARTED'
  | 'EVALUATION_STAGE_CHANGED'
  | 'STATIC_ANALYSIS_STARTED'
  | 'STATIC_ANALYSIS_COMPLETED'
  | 'SANDBOX_STARTED'
  | 'SANDBOX_COMPLETED'
  | 'TEST_CASE_STARTED'
  | 'TEST_CASE_COMPLETED'
  | 'MCP_CONTEXT_STARTED'
  | 'MCP_CONTEXT_COMPLETED'
  | 'ANOMALY_ANALYSIS_STARTED'
  | 'ANOMALY_ANALYSIS_COMPLETED'
  | 'ANOMALY_SCORE_UPDATED'
  | 'MENTOR_ANALYSIS_STARTED'
  | 'MENTOR_ANALYSIS_COMPLETED'
  | 'QA_ANALYSIS_STARTED'
  | 'QA_ANALYSIS_COMPLETED'
  | 'SECURITY_ANALYSIS_STARTED'
  | 'SECURITY_ANALYSIS_COMPLETED'
  | 'A2A_NEGOTIATION_STARTED'
  | 'A2A_ROUND_COMPLETED'
  | 'A2A_CONSENSUS_COMPLETED'
  | 'ADAPTIVE_ANALYSIS_STARTED'
  | 'ADAPTIVE_ANALYSIS_COMPLETED'
  | 'EVALUATION_COMPLETED'
  | 'EVALUATION_FAILED';

export interface RealtimeEvent {
  event_id: string;
  event_type: RealtimeEventType;
  timestamp: string;
  attempt_id?: string;
  submission_id?: string;
  sequence_number: number;
  progress?: number;
  payload: Record<string, any>;
}
