apiVersion: v1
kind: Service
metadata:
  name: {{ include "multi-agent-exam-portal.fullname" . }}-backend-service
  namespace: {{ .Values.global.namespace }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8000
      targetPort: 8000
  selector:
    app.kubernetes.io/name: {{ include "multi-agent-exam-portal.name" . }}-backend
